//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aspnet_Roles_Rights_Relationship
    {
        public System.Guid Id { get; set; }
        public System.Guid RoleId { get; set; }
        public System.Guid RightId { get; set; }
    
        public virtual aspnet_Rights aspnet_Rights { get; set; }
        public virtual aspnet_Roles aspnet_Roles { get; set; }
    }
}
