//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_News
    {
        public System.Guid NewsId { get; set; }
        public System.Guid NewsCategory { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
        public string WriterId { get; set; }
        public string WriterName { get; set; }
        public string Introduction { get; set; }
        public string Body { get; set; }
        public Nullable<bool> ApprovedStatus { get; set; }
        public Nullable<System.Guid> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOnDate { get; set; }
    
        public virtual aspnet_Membership aspnet_Membership { get; set; }
        public virtual cms_NewsCategory cms_NewsCategory { get; set; }
    }
}
