//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_Post
    {
        public System.Guid PostId { get; set; }
        public System.Guid PostCategoryId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public System.DateTime LastUpdatedOnDate { get; set; }
        public System.Guid UserId { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual cms_PostCategory cms_PostCategory { get; set; }
    }
}
