//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_Video
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string FullPath { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
    }
}
