//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cms_Comment()
        {
            this.cms_Comment1 = new HashSet<cms_Comment>();
        }
    
        public System.Guid CommentId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public System.DateTime LastUpdatedOnDate { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public bool IsApproved { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public Nullable<System.Guid> CommentParentId { get; set; }
        public string Type { get; set; }
        public Nullable<System.Guid> ThreadId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_Comment> cms_Comment1 { get; set; }
        public virtual cms_Comment cms_Comment2 { get; set; }
    }
}
