//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_Bill_API
    {
        public System.Guid Id { get; set; }
        public System.Guid BillId { get; set; }
        public System.Guid APIId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
    
        public virtual cms_API cms_API { get; set; }
        public virtual cms_Bill cms_Bill { get; set; }
    }
}
