//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_UserTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cms_UserTransaction()
        {
            this.cms_UserTransaction_API = new HashSet<cms_UserTransaction_API>();
        }
    
        public System.Guid BillId { get; set; }
        public System.Guid UserId { get; set; }
        public int TotalPrice { get; set; }
        public System.DateTime CreatedOnDate { get; set; }
        public bool Paid { get; set; }
        public Nullable<System.DateTime> PaidOnDate { get; set; }
    
        public virtual aspnet_Membership aspnet_Membership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_UserTransaction_API> cms_UserTransaction_API { get; set; }
    }
}
