//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_APIType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cms_APIType()
        {
            this.cms_API = new HashSet<cms_API>();
        }
    
        public System.Guid APITypeId { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_API> cms_API { get; set; }
    }
}
