//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_API_Membership_Relationship
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> APIId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<System.Guid> AccessToken { get; set; }
        public string AccessCode { get; set; }
    
        public virtual aspnet_Membership aspnet_Membership { get; set; }
        public virtual cms_API cms_API { get; set; }
    }
}
