//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cms_VKTTVEntities : DbContext
    {
        public cms_VKTTVEntities()
            : base("name=cms_VKTTVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Rights> aspnet_Rights { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_Roles_Rights_Relationship> aspnet_Roles_Rights_Relationship { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<cms_News> cms_News { get; set; }
        public virtual DbSet<cms_NewsCategory> cms_NewsCategory { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<cms_API> cms_API { get; set; }
        public virtual DbSet<cms_API_Membership_Relationship> cms_API_Membership_Relationship { get; set; }
        public virtual DbSet<cms_APIType> cms_APIType { get; set; }
        public virtual DbSet<cms_UserTransaction> cms_UserTransaction { get; set; }
        public virtual DbSet<cms_UserTransaction_API> cms_UserTransaction_API { get; set; }
        public virtual DbSet<cms_Comment> cms_Comment { get; set; }
        public virtual DbSet<cms_Post> cms_Post { get; set; }
        public virtual DbSet<cms_PostCategory> cms_PostCategory { get; set; }
        public virtual DbSet<cms_Video> cms_Video { get; set; }
    }
}
